---
# Copyright 2018 widdix GmbH
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
AWSTemplateFormatVersion: '2010-09-09'
Description: 'cfn-modules: AWS Lambda event source: webhook'
# cfn-modules:implements()
Parameters:
  LambdaModule:
    Description: 'Stack name of lambda-function module.'
    Type: String
  AlertingModule:
    Description: 'Optional but recommended stack name of alerting module.'
    Type: String
    Default: ''
Conditions:
  HasAlertingModule: !Not [!Equals [!Ref AlertingModule, '']]
Resources:
  Permission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: {'Fn::ImportValue': !Sub '${LambdaModule}-Name'}
      Principal: 'apigateway.amazonaws.com'
      SourceArn: !Sub 'arn:${AWS::Partition}:execute-api:${AWS::Region}:${AWS::AccountId}:${Api}/*/$default'
  Api:
    Type: 'AWS::ApiGatewayV2::Api'
    Properties:
      Name: !Ref 'AWS::StackName'
      ProtocolType: HTTP
      Target: !Sub
      - 'arn:${Partition}:apigateway:${Region}:lambda:path/2015-03-31/functions/${LambdaFunctionArn}/invocations'
      - Partition: !Ref 'AWS::Partition'
        Region: !Ref 'AWS::Region'
        LambdaFunctionArn: {'Fn::ImportValue': !Sub '${LambdaModule}-Arn'}
  Alarm5XXErrorTooHigh:
    Condition: HasAlertingModule
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmDescription: 'Api Gateway server-side errors captured'
      Namespace: 'AWS/ApiGateway'
      MetricName: 5xx
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 1
      ComparisonOperator: GreaterThanThreshold
      Threshold: 0
      AlarmActions:
      - 'Fn::ImportValue': !Sub '${AlertingModule}-Arn'
      Dimensions:
      - Name: ApiId
        Value: !Ref Api
      - Name: Stage
        Value: '$default'
      TreatMissingData: notBreaching
Outputs:
  ModuleId:
    Value: 'lambda-event-source-webhook'
  ModuleVersion:
    Value: '2.0.0'
  StackName:
    Value: !Ref 'AWS::StackName'
  Url:
    Value: !GetAtt 'Api.ApiEndpoint'
    Export:
      Name: !Sub '${AWS::StackName}-Url'
